credentials:
  usernames:
    ti:
      email: ti@nicopel.com.br
      name: TI
      password: "$2b$12$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" # Mantenha seu hash original
    qualidade:
      email: qualidade@nicopel.com.br
      name: Qualidade
      password: "$2b$12$YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY" # Mantenha seu hash original
cookie:
  expiry_days: 1
  key: random_signature_key # Idealmente, esta chave deve ser um segredo complexo
  name: dashboard_cookie
preauthorized:
  emails:
  - ti@nicopel.com.br
  - qualidade@nicopel.com.br